name: test-forcepush
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ccwienk/cc-utils # explicit is better than implicit
      - uses: ccwienk/cc-utils/.github/actions/setup-git-identity@master
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: 1216611
          private-key: ${{ secrets.AUTH_APP_KEY }}
      - name: test-forcepush
        shell: bash
        run: |
          git commit --allow-empty -m "test commit"

          git config -l
          echo -------

          git push origin +@:refs/heads/tmp
